package CorbaQuiz;


/**
* CorbaQuiz/App.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* dimanche 2 décembre 2018 22 h 13 GMT+01:00
*/

public interface App extends AppOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface App
