package CorbaQuiz;

/**
* CorbaQuiz/AppHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* dimanche 2 décembre 2018 22 h 13 GMT+01:00
*/

public final class AppHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaQuiz.App value = null;

  public AppHolder ()
  {
  }

  public AppHolder (CorbaQuiz.App initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaQuiz.AppHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaQuiz.AppHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaQuiz.AppHelper.type ();
  }

}
