package CorbaQuiz;


/**
* CorbaQuiz/AppOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* dimanche 2 décembre 2018 22 h 13 GMT+01:00
*/

public interface AppOperations 
{
  void setQuiz (CorbaQuiz.Quiz q);
  void updateQuiz (CorbaQuiz.Quiz q);
  CorbaQuiz.Quiz[] getQuiz ();
  CorbaQuiz.Quiz getQuestion (int id);
} // interface AppOperations
