package CorbaQuiz;


/**
* CorbaQuiz/AppPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* dimanche 2 décembre 2018 22 h 13 GMT+01:00
*/

public abstract class AppPOA extends org.omg.PortableServer.Servant
 implements CorbaQuiz.AppOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("setQuiz", new java.lang.Integer (0));
    _methods.put ("updateQuiz", new java.lang.Integer (1));
    _methods.put ("getQuiz", new java.lang.Integer (2));
    _methods.put ("getQuestion", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CorbaQuiz/App/setQuiz
       {
         CorbaQuiz.Quiz q = CorbaQuiz.qzHelper.read (in);
         this.setQuiz (q);
         out = $rh.createReply();
         break;
       }

       case 1:  // CorbaQuiz/App/updateQuiz
       {
         CorbaQuiz.Quiz q = CorbaQuiz.qzHelper.read (in);
         this.updateQuiz (q);
         out = $rh.createReply();
         break;
       }

       case 2:  // CorbaQuiz/App/getQuiz
       {
         CorbaQuiz.Quiz $result[] = null;
         $result = this.getQuiz ();
         out = $rh.createReply();
         CorbaQuiz.qzsequenceHelper.write (out, $result);
         break;
       }

       case 3:  // CorbaQuiz/App/getQuestion
       {
         int id = in.read_long ();
         CorbaQuiz.Quiz $result = null;
         $result = this.getQuestion (id);
         out = $rh.createReply();
         CorbaQuiz.QuizHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CorbaQuiz/App:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public App _this() 
  {
    return AppHelper.narrow(
    super._this_object());
  }

  public App _this(org.omg.CORBA.ORB orb) 
  {
    return AppHelper.narrow(
    super._this_object(orb));
  }


} // class AppPOA
