package CorbaQuiz;

/**
* CorbaQuiz/QuizHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* dimanche 2 décembre 2018 22 h 13 GMT+01:00
*/

public final class QuizHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaQuiz.Quiz value = null;

  public QuizHolder ()
  {
  }

  public QuizHolder (CorbaQuiz.Quiz initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaQuiz.QuizHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaQuiz.QuizHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaQuiz.QuizHelper.type ();
  }

}
