package CorbaQuiz;


/**
* CorbaQuiz/qzsequenceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from quiz.idl
* dimanche 2 décembre 2018 22 h 13 GMT+01:00
*/

abstract public class qzsequenceHelper
{
  private static String  _id = "IDL:CorbaQuiz/qzsequence:1.0";

  public static void insert (org.omg.CORBA.Any a, CorbaQuiz.Quiz[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CorbaQuiz.Quiz[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = CorbaQuiz.QuizHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (CorbaQuiz.qzHelper.id (), "qz", __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (CorbaQuiz.qzsequenceHelper.id (), "qzsequence", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CorbaQuiz.Quiz[] read (org.omg.CORBA.portable.InputStream istream)
  {
    CorbaQuiz.Quiz value[] = null;
    int _len0 = istream.read_long ();
    value = new CorbaQuiz.Quiz[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = CorbaQuiz.qzHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CorbaQuiz.Quiz[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      CorbaQuiz.qzHelper.write (ostream, value[_i0]);
  }

}
